# Generated by Django 5.0.1 on 2025-05-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Truck kompaniya ichki raqami (masalan: TRK-245)', max_length=20, unique=True)),
                ('plate_number', models.CharField(blank=True, help_text='Davlat tomonidan berilgan raqam (masalan: TX 98325 AB)', max_length=20, null=True)),
                ('driver_name', models.CharField(blank=True, help_text='Truck haydovchisining to‘liq ismi', max_length=100, null=True)),
                ('vin_number', models.CharField(blank=True, help_text='VIN — Vehicle Identification Number', max_length=50, null=True)),
                ('make', models.CharField(blank=True, help_text='Ishlab chiqaruvchi (masalan: Freightliner, Volvo)', max_length=50, null=True)),
                ('model', models.CharField(blank=True, help_text='Model nomi', max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Yil (masalan: 2020)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', help_text='Truck holati: faol, faol emas yoki texnik xizmatda', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckOrientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done')], default='not_done', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orientation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.orientationtype')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientations', to='truck.truck')),
            ],
            options={
                'unique_together': {('truck', 'orientation_type')},
            },
        ),
    ]
