# Generated by Django 5.0.1 on 2025-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='number',
            field=models.CharField(blank=True, help_text='Truck ichki raqami (masalan: TRK-245)', max_length=100, null=True, unique=True),
        ),
    ]
