# Generated by Django 5.0.1 on 2025-05-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kompaniya nomi (masalan: MUNISA)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Kompaniya hozirda faolmi?')),
            ],
        ),
        migrations.RemoveField(
            model_name='truck',
            name='driver_name',
        ),
        migrations.AlterField(
            model_name='orientationtype',
            name='name',
            field=models.CharField(help_text='Orientation nomi (masalan: DISPATCH)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(blank=True, help_text='Ishlab chiqaruvchi (masalan: Volvo)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, help_text='Model nomi (masalan: VNL)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='number',
            field=models.CharField(help_text='Truck ichki raqami (masalan: TRK-245)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Davlat raqami (masalan: TX 98325 AB)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin_number',
            field=models.CharField(blank=True, help_text='VIN (Vehicle Identification Number)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truckorientation',
            name='status',
            field=models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done')], default='not_done', help_text='Orientation holati', max_length=10),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Haydovchining to‘liq ismi', max_length=100)),
                ('date', models.DateField(help_text='Kiritilgan sana')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', help_text='Driverning hozirgi holati', max_length=10)),
                ('driver_type', models.CharField(blank=True, choices=[('company', 'Company Driver'), ('owner', 'Owner Operator'), ('reefer', 'Reefer Driver')], help_text='Driver turi', max_length=10, null=True)),
                ('confirmation', models.CharField(blank=True, help_text='Confirmation status', max_length=100, null=True)),
                ('sign', models.CharField(blank=True, help_text='Sign (masalan: signed)', max_length=50, null=True)),
                ('docusign', models.CharField(blank=True, help_text='DocuSign status', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck.company')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck.truck')),
            ],
        ),
    ]
