# Generated by Django 5.0.1 on 2025-05-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_company_remove_truck_driver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(help_text='Group id', max_length=100, unique=True)),
            ],
        ),
    ]
