# Generated by Django 5.0.1 on 2025-05-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_allowedgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Holat nomi (masalan: Enroute, In Maintenance, Active)', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck.company'),
        ),
        migrations.AddField(
            model_name='truck',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='st',
            field=models.CharField(blank=True, help_text='ST (masalan: TX, IL)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='tm_or_b',
            field=models.CharField(blank=True, help_text='TM/B (masalan: AT, MT)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='whose_truck',
            field=models.CharField(blank=True, help_text='Whose Truck (masalan: Owner)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Truck status (masalan: Enroute)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='truck.truckstatus'),
        ),
    ]
