# Generated by Django 5.0.1 on 2025-05-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_truckstatus_truck_color_truck_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('annual_inspection', models.CharField(max_length=20)),
                ('rental_agreement', models.CharField(max_length=20)),
                ('outbound_inspection', models.CharField(max_length=20)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='truck.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_of_ownership', models.BooleanField(default=False)),
                ('safety_carrier', models.BooleanField(default=False)),
                ('liability_and_cargo', models.BooleanField(default=False)),
                ('physical_damage', models.BooleanField(default=False)),
                ('physical_exp', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='truck.truck')),
            ],
        ),
    ]
