# Generated by Django 5.0.1 on 2025-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_truckinspection_truckinsurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Davlat raqami (masalan: TX 98325 AB)', max_length=50, null=True),
        ),
    ]
